### PR TITLE
Update RedHat master.cf to RHEL7

### PR DESCRIPTION
**Pull request by gcoxmoz**
As mentioned in #219 there are a number of places where the puppet-pushed master.cf differs from the one provided by a default install.

Using #219 as a starting point I've gone through and made a series of small commits so that it's fairly obvious what changes are being made.  The idea here is to modernize the puppet config, and reduce the differences experienced during an initial puppetization of a pristine host.

### CODE REVIEW

**Comment by raphink** [comment]
I really need to tackle that change… That said, it's a backward incompatible change, so I keep pushing it. @mcanevet what do you think?

**Comment by gcoxmoz** [comment]
worthless comment to stave off stalebot.

**Comment by vchepkov** [comment]
Curious, why have bunch of erb files instead of one general epp template with configurable sections?

**Comment by gcoxmoz** [comment]
I edited the erb file that was already in the repo.   I'm not opposed to doing it some other way, but considering stalebot is the most engagement I'm seeing from camptocamp, I'm not inclined to pour more time on a reengineering effort if they're not interested in PRs.

**Comment by vchepkov** [comment]
It was a general question, not to this particular PR.
btw, fedora and rhel8 also have similar config

**Comment by gcoxmoz** [comment]
Dear Bot Maintainer,
You've called this PR out for failing -travis-, which hasn't worked for a year.  I don't think anyone is seriously looking at any PRs here.
I was already miffed that this was getting nitpicked.
You win.

**Pull request closed without merging**
