### PR TITLE
postfix-ldap required for ldap lookup type on RHEL8+

### LINKED ISSUE #397: missing postfix-ldap rpm on RHEL8+ distro
## Affected Puppet, Ruby, OS and module versions/distributions

- Distribution: RHEL 9
- Module version: 4.4.0

## How to reproduce (e.g Puppet code you use)
set ldap to true in the init class and configure postfix to use ldap

## What are you seeing
on RHEL9 postfix-ldap rpm is required if you want to use the ldap lookup type. The module only includes that package if [os][family] fact is 'Debian'.

## What behaviour did you expect instead
When ldap is set to true in the init class the postfix-ldap rpm should be installed when using RHEL9. Looks like this changed from RHEL7 to RHEL8 (also postfix 2 to postfix 3) so versions greater than 7 should all do this.

### PR DESCRIPTION
**Pull request by edrude**
#### Pull Request (PR) description
Install postfix-ldap package when ldap=true on RHEL8+

#### This Pull Request (PR) fixes the following issues
Fixes #397

### CODE REVIEW

**Review by kenyon — COMMENTED** [review]
Wouldn't it be better to use the module's hiera data for this kind of thing rather than using conditionals in code?

**Comment by smortex** [comment]
> Wouldn't it be better to use the module's hiera data for this kind of thing rather than using conditionals in code?

+1: some `Array[String[1]] $ldap_packages` parameter with the right default values in hiera and a `package { $postfix::ldap_packages: ensure => installed }' in the manifest seems more flexible.

**Comment by edrude** [comment]
Absolutely, I was just trying to get something down. If I get some time tomorrow I will update it.

**Comment by edrude** [comment]
Made the suggested changes. 

One thing I have been struggling with when using this module. I find a few options that would appear at first to be useful for me, but end up being too opinionated. $mta and $ldap are both examples.

In the case of $ldap I want my ldap lookups to be a part of 'virtual_alias_maps' instead of 'alias_maps', but if $ldap = true the ldap config file is added to the 'alias_maps' option.

I also can't use $mta because if $mta = true then 'virtual_alias_maps' is set for me.

I see the merit of building in some common opinionated scenarios, maybe this is more of a documentation issue. If the docs had some callout to "these options are equivalent to" or "opinionated setup of" I think I would have arrived where I am now much faster.

Specifically for $ldap it may make sense to separate out the installation of the $ldap_packages so that you can still "enable ldap" without doing everything that setting $ldap to true does. Anything that separates out "making postfix ready to use ldap" from "configuring how postfix uses ldap"

**Review by kenyon — APPROVED** [review]

**Review by smortex — APPROVED** [review]

**Comment by smortex** [comment]
> One thing I have been struggling with when using this module. I find a few options that would appear at first to be useful for me, but end up being too opinionated. $mta and $ldap are both examples.

I quite agree. On one hand some interfaces are really not great IMHO, but on the other hand we don't want to break the setup of users of the module.  It is hard to change things when they are done in a certain way.  That being said, I think that all efforts to make diving in with the module are good to have.  Feel free to send PRs.

**Pull request merged**
